# Generated by Django 2.2.5 on 2020-05-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200527_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='currecy',
            new_name='currency',
        ),
    ]
